FROM python:3.12-slim

WORKDIR /app

COPY task_manager/backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY task_manager/backend/app/ .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
